### ISSUE TITLE
Set a NPC Player health

### ISSUE THREAD

**Issue by kangarko** [CitizensDev/CitizensAPI#77]
What is the best way to set a Player NPC max health?

I have a user wanting to increase the default Player NPCs health. I have tried:

`fakePlayer.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(boss.getMaxHealth());`

or 

`fakePlayer.setHealth(boss.getMaxHealth());`

Where the fakePlayer being NPC#getEntity() casted to a Player.

To no avail, and even if the health appeared to be changed it is lost and reset back to 20HP after a restart.

Thank you.
Matej

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues is preferred for Citizens questions on github, or Discord @ https://discord.gg/Q6pZGSR

You can add a Trait that assigns maxHealth to the entity onSpawn. 
For example, see how Sentinel does it here:
https://github.com/mcmonkeyprojects/Sentinel/blob/95071f847275af34c32878989b563ecce44d858d/src/main/java/org/mcmonkey/sentinel/SentinelTrait.java#L1831-L1836

**Comment by kangarko** [comment]
Thank you, appreciated your fast reply.

I have created the trait however, upon shutting the server down with /stop and starting it again, the health is reset. Also, after updating a NPC's skin, the same happens. 

Looks like the onSpawn() is called twice in your code: 

![a](https://i.imgur.com/JC68nnc.png)

I have attempted to save a boolean flag to prevent duplicate calls but that does not work since Citizens appears not to remember the actual entity health, i.e. it gets reset. What I am doing wrong please?

**Comment by mcmonkey4eva** [comment]
`onSpawn` is called whenever the NPC is spawned.

In your case, it was first called by your own `Boss.spawn` creating it, and then called a second time by the `Skin` trait - this is likely because you either did not set a skin for the NPC (ie it will download the default skin for the NPC), or set it *after* spawning - in either case, this requires a respawn to apply the skin once one is loaded.
You can avoid that by calling `setSkinPersistent` prior to spawning to give it a skin in advance - https://wiki.citizensnpcs.co/Skins

You shouldn't, however, need to prevent duplicate calls - you should, uh, just do the correct behavior in the method and avoid secondary behaviors.
You can store the intended health value as an `@Persist` field on the trait if you want to avoid your `Boss.findBoss` code being called repeatedly.

Each time the NPC spawns its a new entity, and its the duty of trait `onSpawn` calls to configure the new entity according to the trait's requirements.

**Comment by kangarko** [comment]
Thank you, I appreciate you fast reply. I removed my plugin and installed Sentinel, the NPC's health is still reset after /stop and starting the server again, I made a quick video to demonstrate it here: https://www.loom.com/share/c026a0b09e444694b469c7c564ac77e7

**Comment by mcmonkey4eva** [comment]
Sentinel persists the max health, but will reset the current health to full after respawn.
It appears in that video to be doing exactly that - persisting your preferred max health, and resetting current health to full.

You can store the current health in an `@Persist` field (update it eg in `run()` or `onDespawn` or damage events, wherever you prefer), and then apply that health back in `onSpawn` (just to be sure to set max health THEN current health, not the reverse, or it'll bug out for healths above 20).

**Comment by kangarko** [comment]
Thank you, I was not aware that resetting the current health was intentional. I am going to attempt to manually store it and then set it back.

**Comment by kangarko** [comment]
Done! If anyone needs a similar solution, here is my code: https://pastebin.com/ZbUkJDBK (You will need to set the Entity's health equal to max health outside of this class in your own method after calling NPC#spawn() to make it fully functional as well as get my class' trait and update health field after you do it)
